SELECT
	 COUNT(FALL_SMSTR) AS FALL_2020
	,COUNT(SPRING_SMSTR) AS SPRING_2020
	,ROUND(COUNT(SPRING_SMSTR) / COUNT(FALL_SMSTR) * 100, 2) AS PERSISTENCE_RATE
FROM
	(WITH FALL_CENSUS (STUDENT_PID, STUDENT_CAREER, STUDENT_CAMPUS_DETAIL_DESC, TERM_CODE) 
	AS (

-- FALL 2019 CENSUS
		SELECT STUDENT_PID
			,STUDENT_CAREER
			,STUDENT_CAMPUS_DETAIL_DESC
			,TERM_CODE
		FROM
			IEA_DM_STU_ENRL_TERM_V
		WHERE
			STUDENT_CAMPUS_DETAIL_DESC = 'Athens Main Campus'
			AND STUDENT_CAREER = 'Undergraduate'
			AND TERM_CODE = '20201C'),
	
	SPRING_FINAL AS (

-- SPRING 2020 FINAL
	SELECT STUDENT_PID
		,STUDENT_CAREER
		,STUDENT_CAMPUS_DETAIL_DESC
		,TERM_CODE
	FROM
		IEA_DM_STU_ENRL_TERM_V
	WHERE
		STUDENT_CAMPUS_DETAIL_DESC = 'Athens Main Campus'
		AND STUDENT_CAREER = 'Undergraduate'
		AND TERM_CODE = '20203F' )
		
	SELECT FC.STUDENT_PID
		,FC.STUDENT_CAREER
		,FC.STUDENT_CAMPUS_DETAIL_DESC
		,FC.TERM_CODE AS FALL_SMSTR
		,SF.TERM_CODE AS SPRING_SMSTR
		
-- LEFT SELF JOIN 

		FROM FALL_CENSUS FC
		LEFT JOIN SPRING_FINAL SF ON
		FC.STUDENT_PID = SF.STUDENT_PID )